### ISSUE TITLE
Window not resized after switching from `F11` fullscreen mode to maximum window 

### ISSUE THREAD

**Issue by AyakaAgo** [microsoft/WSA#246] opened 2023-03-02 05:12 UTC
### Steps to reproduce

When we first open the app, it open as normal window size:
![0FP@30MYF`_U~31R$S@)R(7](https://user-images.githubusercontent.com/20831549/222334797-57cf9c95-84f8-44ee-8b68-5931acf153c0.png)

When the window is not maximized, press f11 and then press it again to exit full-screen mode, the window will automatically restore to its previous size.

---------------------

Then double click on the title bar to maximize the window:
![O $263X_LC`{CW}@7`8FCLF](https://user-images.githubusercontent.com/20831549/222335917-e19ecd12-34e8-4f00-8b2f-d484a791ae59.png)

press F11 and exit, window doesn't resize to maximized size, so if the user does not resize the window, the content at the bottom (navigation bar, list item, ...) may not visible
![4E4`D _BKI)YB{RI4%)Z8D0](https://user-images.githubusercontent.com/20831549/222335226-62cdad78-c7f5-454a-be14-bde5d18a788a.png)

### ✔️ Expected Behavior

resize window when switching from f11 fullscreen mode to maximum window 
![O $263X_LC`{CW}@7`8FCLF](https://user-images.githubusercontent.com/20831549/222335917-e19ecd12-34e8-4f00-8b2f-d484a791ae59.png)

### ❌ Actual Behavior

window not resized
![4E4`D _BKI)YB{RI4%)Z8D0](https://user-images.githubusercontent.com/20831549/222335226-62cdad78-c7f5-454a-be14-bde5d18a788a.png)

### Please specify the version of Windows Subsystem for Android

2301.40000.7.0

**Comment by AyakaAgo** [comment] 2023-03-02 06:20
`Activity.isInMultiWindowMode` is still `true` after F11, so i also do this

```groovy
//app gradle
dependencies {

    //for kt
    implementation "androidx.window:window:1.0.0"
    //for java
    implementation "androidx.window:window-java:1.0.0"

}
```

java
```java
    @SuppressLint("ObsoleteSdkInt")
    public boolean isInMultiWindowMode(Activity context) {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.M) {
            return false;
        }
        WindowMetricsCalculator calculator = WindowMetricsCalculator.getOrCreate();
        return context.isInMultiWindowMode()
                && !calculator.computeCurrentWindowMetrics(context).getBounds().equals(
                        calculator.computeMaximumWindowMetrics(context).getBounds()
        );
    }
```

kotlin
```kotlin
    @SuppressLint("ObsoleteSdkInt")
    fun isInMultiWindowMode(context: Activity): Boolean = if (Build.VERSION.SDK_INT < Build.VERSION_CODES.M) {
            false
        } else {
            val calculator = WindowMetricsCalculator.getOrCreate()
            context.isInMultiWindowMode &&
                    calculator.computeCurrentWindowMetrics(context).bounds != calculator.computeMaximumWindowMetrics(context).bounds
        }
```

**Comment by philnach** [comment] 2023-03-04 00:37
Thank you for the bug report, I've marked this as needing investigation.  There's another similar reported issue as well: #156.

**Comment by AyakaAgo** [comment] 2023-03-04 16:01
some third-party app may detect freeform mode by `Activity.isInMultiWindowMode()`, but as i say, this method still return `true` after f11, so with this detection, some app function "doesn't" work (such as photo editor in [QQ](https://play.google.com/store/apps/details?id=com.tencent.mobileqq) and full screen video playing in [Bilibili HD](https://www.coolapk.com/apk/tv.danmaku.bilibilihd)).

**Comment by nieubank** [comment] 2023-08-24 16:40
We're tracking this as a duplicate of #260

**Closed by nieubank** 2023-08-24 16:40 UTC
Labels: needs-investigation, bug
