### ISSUE TITLE
Certain APP Screenshot

### ISSUE THREAD

**Issue by schwarzichet** [microsoft/WSA#206] opened 2023-01-12 00:23 UTC
### Is your feature request related to a problem? Please describe

When I try to get a screenshot in WSA using `adb.exe -s 127.0.0.1:58526 exec-out screencap -p > screen.png`, It will show some "correct" but not "needed" behaviors.  

For example, when I run two differernt apps, and try to take a screenshot, it will show
![screen](https://user-images.githubusercontent.com/15522755/211944241-3e868c80-271e-46f5-9bdd-008adf544b7c.png)
There are two overlapping apps.

If there is only one app running, it will show
![screen](https://user-images.githubusercontent.com/15522755/211945546-a4cb1003-c68d-4b61-a93d-8d22240a63c3.png)
screenshot with black border around it. Since WSA's window manager will take Windows monitor resolution as its physical size,  and the screenshot will capture the whole screen.

### Describe the solution you'd like

I wonder if it is possible to provide some api that can screenshot on only certain app with its own window size.

### Please specify the version of Windows Subsystem for Android

2211.40000.11.0

**Comment by hamza-usmani** [comment] 2023-01-25 17:41
Hi, thank you for this feature request. Currently this isn't on our immediate roadmap, but we're always listening to the community!

**Comment by SteveWorkshop** [comment] 2023-05-06 08:01
这好像是wsa的窗口管理模型机制，wsa认为电脑屏幕为其屏幕大小，Windows的窗口被映射为安卓的多窗口。启动器被写死为全黑背景，然后截图自然就这样了

**Comment by nieubank** [comment] 2023-05-22 16:25
Duplicate of #270. This is not something on our immediate roadmap.

**Closed by nieubank** 2023-05-22 16:25 UTC
Labels: by-design, feature-request
