### ISSUE TITLE
The wsa is already not support the ipv6 connections. When the WSA is supporting the ipv6 networking? Even if update a newest version, is not solve this bug.

### ISSUE THREAD

**Issue by yk00365** [microsoft/WSA#395] opened 2023-08-11 11:45 UTC
### Steps to reproduce

1.Open a tool
2.Open the selections for the WSA.
3.Choose About.
4.Watch the IP address.
5.Show this bug, even I open the Advaned Network connections, is not show the current ipv6 address, only the local ipv6 address, I think the "FakeWifi" is not solve this problem. And if you install an android browser, if you check the ipv6 connection,is not support. But my computer network is already support the IPv6 connections, So I think please solve this problem.
<img width="990" alt="image" src="https://github.com/microsoft/WSA/assets/48024266/7f2af4c6-4447-4fbb-8d54-b9fdb2b9194d">

<img width="958" alt="image" src="https://github.com/microsoft/WSA/assets/48024266/f0fafdaf-a375-4df2-8ada-5058c1d18933">

### ✔️ Expected Behavior

The WSA is supporting the IPv6 connection  from the computer's ipv6 connections and can open and support IPv6 apps or websites. 

### ❌ Actual Behavior

Show this bug, even I open the Advaned Network connections, is not show the current ipv6 address, only the local ipv6 address, I think the "FakeWifi" is not solve this problem. And if you install an android browser, if you check the ipv6 connection,is not support. But my computer network is already support the IPv6 connections, So I think please solve this problem. Even if I install the latest version, the WSA's ipv6 connection is not work and only have the local interface's ipv6 address. It is can't open ipv6 only apps.
<img width="958" alt="image" src="https://github.com/microsoft/WSA/assets/48024266/f0fafdaf-a375-4df2-8ada-5058c1d18933">
<img width="990" alt="image" src="https://github.com/microsoft/WSA/assets/48024266/547a2ebb-4684-43e6-aabe-9a2e81f9a3fb">

### Please specify the version of Windows Subsystem for Android

2307.40000.5.0

**Comment by yk00365** [comment] 2023-08-11 12:06
<img width="990" alt="image" src="https://github.com/microsoft/WSA/assets/48024266/249250fc-408f-4dc7-ba01-9cc6840dd7aa">

**Comment by philnach** [comment] 2023-08-15 23:04
@yk00365, thank you for taking the time to provide such detailed feedback along with links to Feedback Hub items.  As you've observed ipv6 isn't something WSA supports today.  ipv6 isn't something on our roadmap. We will add your request to our backlog.

**Comment by yk00365** [comment] 2023-08-16 10:29
> @yk00365, thank you for taking the time to provide such detailed feedback along with links to Feedback Hub items. As you've observed ipv6 isn't something WSA supports today. ipv6 isn't something on our roadmap. We will add your request to our backlog.

<img width="531" alt="image" src="https://github.com/microsoft/WSA/assets/48024266/bd94e47e-f873-405f-90ae-cfbe6a108c31">
But，you've added support for IPv6 networking in WSA version 2205.40000.14.0, which is available for all Windows 11 Insider Builds. More details on the updates can be found here: https://blogs.windows.com/windows-insider/2022/07/06/update-to-windows-subsystem-for-android-on-windows-11-july-2022/!
So,when you are reparing this?

**Comment by jaholme** [comment] 2023-08-16 16:15
duplicate of #389

**Closed by jaholme** 2023-08-16 16:15 UTC
Labels: duplicate, feature-request
