### ISSUE TITLE
play store

### ISSUE THREAD

**Issue by Facuudelvaa** [microsoft/WSA#221] opened 2023-02-05 16:51 UTC
### Is your feature request related to a problem? Please describe

falta de apps

### Describe the solution you'd like

instalador oficial con Google play store

### Describe alternatives you've considered

aptoide

### Please specify the version of Windows Subsystem for Android

2211.40000.10.0

**Comment by jaholme** [comment] 2023-02-08 16:47
Duplicate of #74

**Closed by jaholme** 2023-02-08 16:47 UTC
Labels: duplicate, feature-request
