### ISSUE TITLE
Regarding Keymapping

### ISSUE THREAD

**Issue by lucifer202850D** [microsoft/WSA#185] opened 2022-12-21 14:56 UTC
### Is your feature request related to a problem? Please describe

Hello Developers kindly add shooting games and add keymapping in wsa for shooting games like (PUBG,FF) with custom key option . Now you developing well. All the best for your future growth.

### Describe the solution you'd like

My suggestion is use bluestacks keymapping beacuse the keymapping is good

### Please specify the version of Windows Subsystem for Android

Build 2209.40000.26.0

**Comment by hamza-usmani** [comment] 2022-12-28 21:10
Closing as duplicate of #82

**Closed by hamza-usmani** 2022-12-28 21:10 UTC
Labels: duplicate, feature-request
