### ISSUE TITLE
Whenever I open a link, windows first turns on wsa, Is there a way to change this behavior?

### ISSUE THREAD

**Issue by rp1231** [microsoft/WSA#436] opened 2023-09-30 05:00 UTC
### Is your feature request related to a problem? Please describe

Whenever I open a link, windows first turns on wsa, Is there a way to change this behavior?

### Describe the solution you'd like

I would like the link to directly open the default app specified in windows 11 rather than checking wsa apps first.

### Please specify the version of Windows Subsystem for Android

2309.40000.2.0

**Comment by Syping** [comment] 2023-10-03 11:14
Having the same issue, it's really annoying when i click a link and WSA just turns on, a partial workaround was taking away the app permission for the URLs, but it only works temporarily, because after rebooting the PC clicking the links will turn WSA on again, even when it still says the app don't have permission to open these URLs.

**Comment by jaholme** [comment] 2023-10-04 01:16
Duplicate of #342

**Closed by jaholme** 2023-10-04 01:16 UTC
Labels: triage-needed, feature-request
