### ISSUE TITLE
Inconsistencies in Contrast Levels of Videos.

### ISSUE THREAD

**Issue by 7gxycn08** [microsoft/WSA#233] opened 2023-02-14 16:13 UTC
### Steps to reproduce

Run a Youtube Video from a browser on Windows 11 and the same video from Youtube app running in WSA.

### ✔️ Expected Behavior

WSA Contrast level should be equivalent to the one set by Windows 11.

### ❌ Actual Behavior

Videos look washed out when viewed inside an app using WSA. Tested the Youtube Android app vs the same video running in a Chrome browser.

Top Video Is Chrome. Bottom Video Is Youtube App In WSA.
![srgb](https://user-images.githubusercontent.com/121936658/218792893-1c57863e-8995-4c7a-a3b9-3203732f6c07.png)

### Other Software

Youtube Android App 18.05.35

### Please specify the version of Windows Subsystem for Android

2301.40000.4.0

**Comment by wrightwriter** [comment] 2023-02-15 15:27
duplicate: https://github.com/microsoft/WSA/issues/171

I have this issue as well on rtx 3060. It seems there is no inverse gamma correction being applied.

**Comment by jaholme** [comment] 2023-02-15 23:25
duplicate of #171

**Closed by jaholme** 2023-02-15 23:25 UTC
Labels: duplicate, bug
