### ISSUE TITLE
Can you upgrade 'Android OpenGL ES 3.0' to 'Android OpenGLES 3.2'+？

### ISSUE THREAD

**Issue by mengshenup** [microsoft/WSA#353] opened 2023-07-05 09:40 UTC
### Is your feature request related to a problem? Please describe

Can you upgrade 'Android OpenGL ES 3.0' to 'Android OpenGL ES 3.2'+？
Because the app crashes, only '...Android OpenGL ES 3.2'+ is supported
I ran the "Device Info HW.apk" query and found that WSA2305.40000.6.0 showed OpenGL ES 3.0
news, UE5.2 game engine, minimum support for Android 8.0(API 26)[2017-08-21, released], may upgrade to a higher version better, upgrade OpenGL ES

### Describe the solution you'd like

upgrade 'Android OpenGL ES 3.0' to 'Android OpenGL ES 3.2'+

### Describe alternatives you've considered

upgrade 'Android OpenGL ES 3.0' to 'Android OpenGL ES 3.2'+

### Please specify the version of Windows Subsystem for Android

2305.40000.6.0

**Comment by kevinkieselbach** [comment] 2023-07-05 19:51
This is an issue we're tracking.  We make improvements to our graphics stack regularly and are investigating options for supporting a wider range of OpenGL versions if possible.

**Comment by nieubank** [comment] 2023-07-18 23:51
Closing as duplicate of #211

**Closed by nieubank** 2023-07-18 23:51 UTC
Labels: feature-request
