### ISSUE TITLE
Allow apps to draw over windows UI - Screen recording apps

### ISSUE THREAD

**Issue by Mitia99** [microsoft/WSA#344] opened 2023-06-29 13:17 UTC
### Is your feature request related to a problem? Please describe

So I'd like to record my windows screen with android screen recording apps.

I find them more convenient cause they are lighter and offer some quite good features (arrow, shapes...)

![image](https://github.com/microsoft/WSA/assets/56766778/656c74a4-dbb6-481f-a435-559d7ce01bba)

The issue is that the apps can only detect WSA UI not Windows
![image](https://github.com/microsoft/WSA/assets/56766778/1443061c-5bb2-4473-9787-35b620f2d20c)

### Describe the solution you'd like

Allow draw over windows UI so that it detects both Windows and WSA UI.

### Please specify the version of Windows Subsystem for Android

2305.40000.2.0

**Comment by jaholme** [comment] 2023-06-29 20:44
Duplicate of #270

**Closed by jaholme** 2023-06-29 20:44 UTC
Labels: triage-needed, feature-request
