### ISSUE TITLE
Google Play Store Support

### ISSUE THREAD

**Issue by GeorgeWL** [microsoft/WSA#419] opened 2023-09-03 22:18 UTC
### Describe the solution you'd like

please add this

### Please specify the version of Windows Subsystem for Android

latest

**Comment by cranstantinople** [comment] 2023-09-05 01:41
Yes!  Was able to install this using WSAMagisk but would be awesome if it was the default store.  Amazon Store just doesn't have the App selection of Google Play.

**Comment by jaholme** [comment] 2023-09-07 00:14
Duplicate of #74

**Closed by jaholme** 2023-09-07 00:14 UTC
Labels: triage-needed, feature-request
