### ISSUE TITLE
When add the ipv6 support for WSA? 

### ISSUE THREAD

**Issue by yk00365** [microsoft/WSA#471] opened 2023-11-08 10:44 UTC
### Is your feature request related to a problem? Please describe

ipv6 is not support for the latest version for WSA
Would you can add the support for the ipv6?

### Describe the solution you'd like

WSA must support ipv6.

### Please specify the version of Windows Subsystem for Android

2310.40000.1.0

**Comment by jaholme** [comment] 2023-11-14 22:38
Duplicate of #389

**Closed by jaholme** 2023-11-14 22:38 UTC
Labels: triage-needed, feature-request
