### ISSUE TITLE
WSA messes up the default browser to open a link in Windows

### ISSUE THREAD

**Issue by zhangz22** [microsoft/WSA#361] opened 2023-07-09 23:39 UTC
### Steps to reproduce

Install an android program that has a "open link in app" support, and go to Android settings (`wsa://com.android.settings`),  "`Apps`", find the installed app, and go to "`Open by default`" and then make sure "`Open supported link`" option is enabled (which should be enabled by default). 
![image](https://github.com/microsoft/WSA/assets/26744581/74ebb8da-e9d4-4587-92c0-38e8fa174f71)
![image](https://github.com/microsoft/WSA/assets/26744581/8d0c55bb-9fef-4ca0-bc1f-d0aa71803dfd)

Then in windows, open a web link that can be opened in that app:
![image](https://github.com/microsoft/WSA/assets/26744581/815c0a15-bb43-45b5-bdd0-eff7e430906b)

The following behaviors will also apply when open a link from WSA using "`Windows default preference`", making it impossible to open the link in Windows browsers without manually copy and paste the link to browser address bar.

### ✔️ Expected Behavior

The default web browser of Windows system should be opened and link should be opened in the windows browser, or at least there should be an option to let user choose how to open the link.

### ❌ Actual Behavior

There can be 2 cases of the actual behavior:
1. For some links, it will be open directly in the android app, regardless of whether WSA is running or not. If WSA is not running, it will be started. I think this may also explain #342
2. For some links, a popup windows will show to choose an app to open the link. Possible choices containing WSA and default browser: 
    ![image](https://github.com/microsoft/WSA/assets/26744581/8e984f98-781e-4f36-8eb5-69a45f140e9c)
    If "Windows Subsystem for Android" is chosen, the behavior will be same as 1.
    If the default browser is chosen, the link sometimes will be opened in Windows browser correctly, but sometimes will be opened in its source code file like this:
    ![image](https://github.com/microsoft/WSA/assets/26744581/eafb0b1f-d502-48b6-a725-bbfb66c6377d)

Besides, there's no way to change whether to open the link in Android app through windows settings (Windows 11 Settings -> Apps -> Default apps -> Find the Android app -> Click any of the link types, there will be no other option to choose):
![image](https://github.com/microsoft/WSA/assets/26744581/e163ef8e-c6e1-44f0-905f-00d76ed9a8ec)

### Other Software

The list of apps that I have tested:
- Amazon Shopping
- eBay
- Walmart
- Facebook
- Linkedin
- Instagram

### Please specify the version of Windows Subsystem for Android

2306.40000.1.0

**Comment by pc-v2** [comment] 2023-10-01 06:27
I wonder if "Windows default apps" app in wsa caused this

**Comment by jaholme** [comment] 2023-10-04 01:17
Duplicate of #342

**Closed by jaholme** 2023-10-04 01:17 UTC
Labels: bug

**Comment by TheShark27** [comment] 2024-09-26 15:58
I found a definitive fix after a day troubleshooting this.

1. **Make sure WSA is turned off** before proceeding.
2. **Navigate to the following registry location** in Windows Registry Editor:
   ```
   Computer\HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppModel\SystemAppData\MicrosoftCorporationII.WindowsSubsystemForAndroid_8wekyb3d8bbwe\AppUriHandlers\
   ```
3. **Delete the problematic site keys** under the `AppUriHandlers` folder. For example, delete the `google.com` key if it's causing issues.

### How to Test:
1. In **Google Chrome**, type `microsoft-edge:google.com` in the address bar **while WSA is turned off**.
2. Before the fix, this should open Google through WSA.
3. After the fix, a dialog should pop up asking whether to open with **WSA** or **Chrome**. Select **Chrome**.
4. The first time you do this, it might open a strange XML file, but on the second attempt, the link will work correctly in Chrome.

Just to be sure it won't happen again, I deleted the entire AppUriHandlers folder, so that other links, such as amazon.com, won't open in WSA anymore.
