### ISSUE TITLE
Video colors are off when using dedicated GPU.

### ISSUE THREAD

**Issue by Pawloland** [microsoft/WSA#171] opened 2022-12-09 12:10 UTC
### Steps to reproduce

When using dedicated GPU, the video is too bright, so for example the solid black color looks like grey. When the integrated GPU is used, then the video looks fine. It also displays correctly when using MS Basic Render Driver. It's is a problem, because when using the integrated GPU, performance is much worse than using the dedicated one, so using integrated GPU is not a viable solution.

I made a screen recording to better illustrate the issue. I chose VLC android app (v 3.5.3) and Big Bunny movie (http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_60fps_normal.mp4) as an example. It may help debugging the issue when somebody fixing it would be able to look into the source code, of the app and video.

Please note that it is happening also in different apps and on different hardware, so it's not issue specific to my setup.

https://user-images.githubusercontent.com/59684145/206697292-88bc0c0c-cd8b-457b-9195-29d7b0972fa1.mp4

My hardware:
AMD Ryzen 7 4800 H (iGPU driver ver. 27.20.11032.9001)
Nvidia GeForce GTX 1650 Ti (driver ver. 31.0.15.2698)

### ✔️ Expected Behavior

Video displays correctly no matter the GPU used.

### ❌ Actual Behavior

Video displays incorrectly only when using dedicated GPU.

### Please specify the version of Windows Subsystem for Android

2209.40000.28.0

**Comment by nieubank** [comment] 2022-12-09 16:59
Thanks for reporting this issue, I have a local repro, so we'll investigate and see what's going on here.

**Comment by wrightwriter** [comment] 2023-02-16 11:32
I have this issue as well on rtx 3060. It seems there is no inverse gamma correction being applied.

**Comment by 7gxycn08** [comment] 2023-02-18 06:59
Enabling Gamma correction using adb solves this issue.

**To Enable Gamma Correction:**
`adb shell settings put system display_gamma_mode 1`

**Tor Disable Gamma Correction:**
`adb shell settings put system display_gamma_mode 0 `

![gamma](https://user-images.githubusercontent.com/121936658/219846339-3094a858-ab02-4152-b815-d8f5ff9242c5.png)

**Comment by nieubank** [comment] 2023-03-15 16:24
We have a fix for this internally that should be available with the upcoming 2303 release.

**Comment by Pawloland** [comment] 2023-04-14 14:56
From my testing version 2303.40000.3.0 doesn't include a fix.

**Comment by MustardChef** [comment] 2023-04-14 15:03
> From my testing version 2303.40000.3.0 doesn't include a fix.

It seems so. I think that it will be fixed in the next update.

**Comment by nieubank** [comment] 2023-04-18 16:59
unfortunately, the fix for this regressed other video scenarios. The nvidia hardware decoder is ultimately the root cause of this issue and requires manually configuring the black levels in nvidia's settings. We can investigate alternative solutions to this but nothing in the immediate term.

**Comment by 7gxycn08** [comment] 2023-05-12 06:40
> unfortunately, the fix for this regressed other video scenarios. The nvidia hardware decoder is ultimately the root cause of this issue and requires manually configuring the black levels in nvidia's settings. We can investigate alternative solutions to this but nothing in the immediate term.

Happens even on AMD GPU's im running a 7900xtx and colors are still washed out.

**Comment by nieubank** [comment] 2023-05-23 23:55
We have identified the root cause of this and have a fix in the upcoming 2305 build.

**Comment by 7gxycn08** [comment] 2023-06-03 10:00
> We have identified the root cause of this and have a fix in the upcoming 2305 build.

Just tested 2305 build and the issue is still not fixed.

**Comment by nieubank** [comment] 2023-06-03 15:24
> > We have identified the root cause of this and have a fix in the upcoming 2305 build.
> 
> Just tested 2305 build and the issue is still not fixed.

Can you share a dxdiag from your machine and a logcat collected via adb, what apk you're using and if possible confirm whether this reproduced with a publicly available video like big buck bunny?

Alternatively, if you could file a feedback hub report reproducing the issue that would help identify why the fix didn't work on your setup.

**Comment by 7gxycn08** [comment] 2023-06-03 15:38
> > > We have identified the root cause of this and have a fix in the upcoming 2305 build.
> > 
> > 
> > Just tested 2305 build and the issue is still not fixed.
> 
> Can you share a dxdiag from your machine and a logcat collected via adb, what apk you're using and if possible confirm whether this reproduced with a publicly available video like big buck bunny?
> 
> Alternatively, if you could file a feedback hub report reproducing the issue that would help identify why the fix didn't work on your setup.

Here Is the issue demonstrating the Issue. Official Youtube apk on the right and a web browser on the left same video and you can clearly see the apk app Is washed out.
![WSA-Screenshot](https://github.com/microsoft/WSA/assets/121936658/ad499521-2acc-400a-841c-fc9cbec38530)
[logs&DxDiag.zip](https://github.com/microsoft/WSA/files/11643096/logs.DxDiag.zip)

**Comment by Pawloland** [comment] 2023-06-03 16:45
> We have identified the root cause of this and have a fix in the upcoming 2305 build.

I tested it on one of my machines with nvidia card set in wsa settings and can confirm it works!

**Comment by nieubank** [comment] 2023-06-12 00:03
Fixed in 2305

**Closed by nieubank** 2023-06-12 00:03 UTC
Labels: fix-inbound, bug

**Comment by batuhankrmn** [comment] 2023-10-10 00:18
@nieubank hello, I use latest 2309.40000.2.0 release and have this issue on my end. Graphics card is RTX 3080. Colors of the video are grayed out, I checked YouTube and MX Player, results are same. Is there any chance you can check this issue again? I can provide screenshots or more information If you need.
